import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";
import { headers } from "next/headers";
import "./globals.css";
import { ThemeProvider } from "@/lib/theme-context";

const inter = Inter({ subsets: ["latin"] });
import { DEFAULT_THEME_ID } from "@/lib/themes";
import { ServiceWorkerRegistration } from "@/components/service-worker-registration";
import { OfflineIndicator } from "@/components/OfflineIndicator";
import { PushNotificationInitializer } from "@/components/PushNotificationInitializer";
import ErrorBoundary from "@/components/ErrorBoundary";
import { GlobalNav } from "@/components/GlobalNav";
import { QuickCreateFAB } from "@/components/QuickCreateFAB";

export const metadata: Metadata = {
  title: "Zen Workspace - Composed Productivity Hub",
  description: "A sleek, calming productivity platform for harmonising tasks, notes, and relationships.",
  applicationName: "Zen Workspace",
  manifest: "/manifest.webmanifest",
  appleWebApp: {
    capable: true,
    statusBarStyle: "default",
    title: "Zen Workspace",
  },
};

export const viewport: Viewport = {
  themeColor: "#7199B6",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // The nonce is generated by src/middleware.ts and forwarded via the x-nonce
  // request header. Next.js reads this value internally and stamps it onto the
  // inline <script> tags it injects during SSR / streaming, ensuring those
  // scripts satisfy the nonce-based Content-Security-Policy. Capture it here
  // so it can be passed to any next/script components added in the future.
  const nonce = (await headers()).get('x-nonce') ?? '';
  void nonce; // referenced above; used by next/script components when added

  return (
    <html lang="en" data-theme={DEFAULT_THEME_ID}>
      <body className={inter.className}>
        <a
          href="#main-content"
          className="sr-only focus:not-sr-only focus:absolute focus:top-4 focus:left-4 focus:z-50 focus:px-4 focus:py-2 focus:bg-sage-600 focus:text-white focus:rounded-xl"
        >
          Skip to main content
        </a>
        <ThemeProvider>
          <GlobalNav />
          <QuickCreateFAB />
          {/* pb-28 offsets the floating mobile pill nav; lg:pl-16 offsets the desktop sidebar */}
          <ErrorBoundary>
            <div id="main-content" className="pb-28 lg:pb-0 lg:pl-16">{children}</div>
          </ErrorBoundary>
        </ThemeProvider>
        <ServiceWorkerRegistration />
        <PushNotificationInitializer />
        <OfflineIndicator />
      </body>
    </html>
  );
}
